"""
logging.py - Urban Mobility Backend System
==========================================

LOGGING & AUDITING (Volgens Assignment p.8)

SECURITY FEATURES:
- Encrypted Logs (Assignment p.8-9): Fernet symmetric encryption
- All Activities Logged (Assignment p.8)
- Suspicious Activity Flagging (Assignment p.8)
- Alert System for Unread Suspicious Logs (Assignment p.8)
- Only Readable via System Interface (Assignment p.8-9)

LOG STRUCTURE (Assignment p.8):
No. | Date (DD-MM-YYYY) | Time (HH:MM:SS) | Username | Activity | Additional Info | Suspicious

FUNCTIONS:
- log_activity() - Log an activity
- get_all_logs() - Retrieve all logs (decrypted)
- get_suspicious_logs() - Get only suspicious logs
- get_unread_suspicious_count() - Count unread suspicious logs (for alerts)
- mark_logs_as_read() - Mark current logs as read
- clear_logs() - Clear all logs (Super Admin only)
"""

import csv
from datetime import datetime
from pathlib import Path
from cryptography.fernet import Fernet

# ============================================================================
# CONFIGURATION
# ============================================================================

# Use Path like database.py does
DATA_DIR = Path(__file__).parent / "data"
LOG_FILE = DATA_DIR / "system.log"
FERNET_KEY_FILE = DATA_DIR / "fernet_key.bin"
LAST_CHECK_FILE = DATA_DIR / "last_log_check.txt"


# ============================================================================
# ENCRYPTION FUNCTIONS (Assignment p.8-9)
# ============================================================================


def _get_log_cipher():
    """
    Get Fernet cipher voor log encryption (Assignment p.8-9)

    Security (Assignment):
    - Logs must be encrypted
    - Not readable with text editor
    - Only via system interface

    Returns:
        Fernet: Cipher object
    """
    # Lees Fernet key (generated by database.py)
    if not FERNET_KEY_FILE.exists():
        raise FileNotFoundError(
            f"Fernet key file not found at {FERNET_KEY_FILE}! Run database.py first."
        )

    with open(FERNET_KEY_FILE, "rb") as f:
        key = f.read()

    return Fernet(key)


def _encrypt_log_content(content):
    """
    Encrypt log content met Fernet (Assignment p.8-9)

    Args:
        content (str): Plain text log content

    Returns:
        bytes: Encrypted content
    """
    cipher = _get_log_cipher()
    return cipher.encrypt(content.encode())


def _decrypt_log_content(encrypted_content):
    """
    Decrypt log content met Fernet (Assignment p.8-9)

    Args:
        encrypted_content (bytes): Encrypted log content

    Returns:
        str: Decrypted plain text
    """
    cipher = _get_log_cipher()
    return cipher.decrypt(encrypted_content).decode()


# ============================================================================
# LOG ACTIVITY FUNCTION (Assignment p.8)
# ============================================================================


def log_activity(username, activity, additional_info="", suspicious=False):
    """
    Log an activity to encrypted log file (Assignment p.8)

    LOG STRUCTURE (Assignment p.8):
    No. | Date | Time | Username | Activity | Additional Info | Suspicious

    Security (L02):
    - Uses file I/O (no SQL needed for logs)
    - Entire log file encrypted with Fernet (Assignment p.8-9)

    Args:
        username (str): Username performing action
        activity (str): Description of activity
        additional_info (str): Extra information (optional)
        suspicious (bool): Flag as suspicious (default: False)

    Examples:
        log_activity("super_admin", "Logged in")
        log_activity("john_m_05", "Unsuccessful login", "Wrong password", suspicious=True)
        log_activity("admin01", "New traveler added", "Customer ID: 12345")
    """
    # Create data directory if not exists
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Get current log number
    log_number = 1
    if LOG_FILE.exists():
        # Read existing logs om hoogste nummer te vinden
        try:
            with open(LOG_FILE, "rb") as f:
                encrypted_content = f.read()
            decrypted_content = _decrypt_log_content(encrypted_content)
            lines = decrypted_content.strip().split("\n")
            if len(lines) > 1:  # Skip header
                last_line = lines[-1]
                log_number = int(last_line.split(",")[0].strip('"')) + 1
        except Exception:
            log_number = 1

    # Get current date and time
    now = datetime.now()
    date_str = now.strftime("%d-%m-%Y")  # DD-MM-YYYY (Assignment format)
    time_str = now.strftime("%H:%M:%S")  # HH:MM:SS (Assignment format)

    # Suspicious flag
    suspicious_str = "Yes" if suspicious else "No"

    # Create log entry (CSV format)
    log_entry = [
        str(log_number),
        date_str,
        time_str,
        username,
        activity,
        additional_info,
        suspicious_str,
    ]

    # Read existing logs (decrypt if exists)
    existing_content = ""
    if LOG_FILE.exists():
        try:
            with open(LOG_FILE, "rb") as f:
                encrypted_content = f.read()
            existing_content = _decrypt_log_content(encrypted_content)
        except Exception:
            # If decryption fails, start fresh with header
            existing_content = (
                "No.,Date,Time,Username,Activity,Additional Info,Suspicious\n"
            )
    else:
        # First log - add header
        existing_content = (
            "No.,Date,Time,Username,Activity,Additional Info,Suspicious\n"
        )

    # Append new log entry
    log_line = ",".join(f'"{field}"' for field in log_entry)
    new_content = existing_content + log_line + "\n"

    # Encrypt and write (Assignment p.8-9: logs must be encrypted)
    encrypted_content = _encrypt_log_content(new_content)
    with open(LOG_FILE, "wb") as f:
        f.write(encrypted_content)


# ============================================================================
# RETRIEVE LOGS FUNCTIONS (Assignment p.8)
# ============================================================================


def get_all_logs():
    """
    Retrieve all logs (decrypted) voor admin viewing

    Security:
    - Only callable by admins (check should be done in calling code with check_permission)
    - Decrypts logs from encrypted file

    Returns:
        list: List of log dictionaries

    Example:
        logs = get_all_logs()
        for log in logs:
            print(f"{log['no']}: {log['username']} - {log['activity']}")
    """
    if not LOG_FILE.exists():
        return []

    try:
        # Read and decrypt log file
        with open(LOG_FILE, "rb") as f:
            encrypted_content = f.read()

        decrypted_content = _decrypt_log_content(encrypted_content)

        # Parse CSV
        lines = decrypted_content.strip().split("\n")
        if len(lines) <= 1:  # Only header or empty
            return []

        logs = []
        reader = csv.DictReader(lines)
        for row in reader:
            logs.append(
                {
                    "no": int(row["No."]),
                    "date": row["Date"],
                    "time": row["Time"],
                    "username": row["Username"],
                    "activity": row["Activity"],
                    "additional_info": row["Additional Info"],
                    "suspicious": row["Suspicious"],
                }
            )

        return logs

    except Exception as e:
        print(f"Error reading logs: {e}")
        return []


def get_suspicious_logs():
    """
    Get only suspicious logs (Assignment p.8)

    Returns:
        list: List of suspicious log dictionaries

    Example:
        suspicious = get_suspicious_logs()
        if suspicious:
            print("⚠️  SECURITY ALERTS:")
            for log in suspicious:
                print(f"  - {log['activity']} by {log['username']}")
    """
    all_logs = get_all_logs()
    return [log for log in all_logs if log["suspicious"] == "Yes"]


def get_unread_suspicious_count():
    """
    Count unread suspicious activities (Assignment p.8)

    Assignment Quote:
    "produce an alert/notification for unread suspicious activities
     once a System Administrator or Super Administrator is logged in"

    Returns:
        int: Number of unread suspicious logs

    Example:
        count = get_unread_suspicious_count()
        if count > 0:
            print(f"⚠️  WARNING: {count} unread suspicious activities!")
    """
    # Get last checked log number
    last_checked = 0
    if LAST_CHECK_FILE.exists():
        try:
            with open(LAST_CHECK_FILE, "r") as f:
                last_checked = int(f.read().strip())
        except Exception:
            last_checked = 0

    # Get all suspicious logs
    suspicious_logs = get_suspicious_logs()

    # Count unread (logs with number > last_checked)
    unread_count = sum(1 for log in suspicious_logs if log["no"] > last_checked)

    return unread_count


def mark_logs_as_read():
    """
    Mark all current logs as read (Assignment p.8)

    Called when admin views logs.
    Updates last_log_check.txt with highest log number.

    Example:
        mark_logs_as_read()  # Called after admin views logs
    """
    logs = get_all_logs()
    if not logs:
        return

    # Get highest log number
    highest_log_no = max(log["no"] for log in logs)

    # Save to file
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    with open(LAST_CHECK_FILE, "w") as f:
        f.write(str(highest_log_no))


# ============================================================================
# CLEAR LOGS (Super Admin Only - Assignment)
# ============================================================================


def clear_logs():
    """
    Clear all logs - Super Admin only (Assignment)

    Returns:
        tuple: (success, message)

    Security:
    - Should only be called after permission check with check_permission("view_logs")
    - Removes log file and last check file

    Example:
        from auth import check_permission
        if check_permission("view_logs"):
            success, message = clear_logs()
    """
    try:
        # Remove log file
        if LOG_FILE.exists():
            LOG_FILE.unlink()

        # Remove last check file
        if LAST_CHECK_FILE.exists():
            LAST_CHECK_FILE.unlink()

        return True, "All logs cleared successfully"

    except Exception as e:
        return False, f"Error clearing logs: {e}"


# ============================================================================
# DISPLAY FUNCTIONS (Helper)
# ============================================================================


def display_logs(logs, show_suspicious_only=False):
    """
    Display logs in formatted table (Helper function)

    Args:
        logs (list): List of log dictionaries
        show_suspicious_only (bool): Filter suspicious logs

    Example:
        logs = get_all_logs()
        display_logs(logs)
    """
    if show_suspicious_only:
        logs = [log for log in logs if log["suspicious"] == "Yes"]

    if not logs:
        print("No logs found.")
        return

    # Header
    print("\n" + "=" * 140)
    print(
        f"{'No.':<5} | {'Date':<12} | {'Time':<10} | {'Username':<15} | {'Activity':<25} | {'Additional Info':<30} | {'Suspicious':<10}"
    )
    print("=" * 140)

    # Logs
    for log in logs:
        print(
            f"{log['no']:<5} | {log['date']:<12} | {log['time']:<10} | {log['username']:<15} | {log['activity']:<25} | {log['additional_info']:<30} | {log['suspicious']:<10}"
        )

    print("=" * 140)
    print(f"Total logs: {len(logs)}")

    # Show suspicious count
    suspicious_count = sum(1 for log in logs if log["suspicious"] == "Yes")
    if suspicious_count > 0:
        print(f"⚠️  Suspicious activities: {suspicious_count}")


# ============================================================================
# MAIN - Voor testing
# ============================================================================

if __name__ == "__main__":
    print("=" * 60)
    print("LOGGING SYSTEM TESTING")
    print("=" * 60)

    # Test 1: Log normal activities
    print("\n--- Test 1: Logging Normal Activities ---")
    log_activity("super_admin", "Logged in")
    log_activity("super_admin", "New admin user is created", "username: john_m_05")
    log_activity("john_m_05", "Logged in")
    log_activity("john_m_05", "New traveler added", "Customer ID: 12345")
    print("✅ Logged 4 normal activities")

    # Test 2: Log suspicious activities
    print("\n--- Test 2: Logging Suspicious Activities ---")
    log_activity(
        "unknown",
        "Unsuccessful login",
        "username: 'admin' with wrong password",
        suspicious=True,
    )
    log_activity(
        "unknown",
        "Unsuccessful login",
        "Multiple login attempts detected",
        suspicious=True,
    )
    print("✅ Logged 2 suspicious activities")

    # Test 3: Retrieve all logs
    print("\n--- Test 3: Retrieve All Logs ---")
    all_logs = get_all_logs()
    display_logs(all_logs)

    # Test 4: Get suspicious logs only
    print("\n--- Test 4: Suspicious Logs Only ---")
    suspicious = get_suspicious_logs()
    print(f"Found {len(suspicious)} suspicious logs:")
    display_logs(suspicious)

    # Test 5: Unread suspicious count
    print("\n--- Test 5: Unread Suspicious Count ---")
    unread_count = get_unread_suspicious_count()
    print(f"⚠️  Unread suspicious activities: {unread_count}")

    # Test 6: Mark as read
    print("\n--- Test 6: Mark Logs as Read ---")
    mark_logs_as_read()
    print("✅ Logs marked as read")

    # Check unread count again
    unread_count = get_unread_suspicious_count()
    print(f"Unread suspicious activities after marking: {unread_count}")

    # Test 7: Add new suspicious log
    print("\n--- Test 7: New Suspicious Log After Read ---")
    log_activity(
        "unknown",
        "Brute force attack detected",
        "100+ failed attempts",
        suspicious=True,
    )
    unread_count = get_unread_suspicious_count()
    print(f"⚠️  New unread suspicious activities: {unread_count}")

    # Test 8: Verify encryption
    print("\n--- Test 8: Verify Log File is Encrypted ---")
    if LOG_FILE.exists():
        with open(LOG_FILE, "rb") as f:
            raw_content = f.read()[:100]  # First 100 bytes

        print(f"Raw file content (first 100 bytes): {raw_content}")
        print("✅ Log file is encrypted (not human-readable)")

    print("\n" + "=" * 60)
    print("✅ Logging system ready!")
    print("=" * 60)
    print("\n📋 IMPORTANT FOR DEMO:")
    print("   - Logs are encrypted met Fernet (Assignment p.8-9)")
    print("   - Only readable via system interface (niet met text editor)")
    print("   - Suspicious activities flagged and tracked (Assignment p.8)")
    print("   - Alert system voor unread suspicious logs (Assignment p.8)")
